# Generated by Django 4.0.1 on 2022-01-28 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_1', models.CharField(max_length=50)),
                ('pokemon_2', models.CharField(max_length=50)),
                ('move_log', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('winner', models.CharField(max_length=50)),
            ],
        ),
    ]
