# Generated by Django 4.0.1 on 2022-01-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
