# Generated by Django 4.0.1 on 2022-01-29 03:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_battle_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='move_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None),
        ),
    ]
