# Generated by Django 4.0.1 on 2022-02-03 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_battle_move_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='move_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=350), size=None),
        ),
    ]
